=== koa/hs485-comm/src/main/resources/ch/eleveneye/hs485/config/HS485-Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.eleveneye.ch/HS485-Schema"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.eleveneye.ch/HS485-Schema">

	<element name="hs485" type="tns:hs485ComplexType"></element>

	<complexType name="hs485ComplexType">
		<sequence>
			<element name="module" type="tns:moduleType"
				maxOccurs="unbounded" minOccurs="0">
			</element>
		</sequence>
	</complexType>

	<complexType name="moduleType">
		<sequence>
			<element name="input" type="tns:inputType"
				maxOccurs="unbounded" minOccurs="0">
			</element>
			<element name="output" type="tns:outputType"
				maxOccurs="unbounded" minOccurs="0">
			</element>
			<element name="variable" type="tns:variableType"
				maxOccurs="unbounded" minOccurs="0">
			</element>
		</sequence>
		<attribute name="hw-ver" type="int" use="required"></attribute>
		<attribute name="sw-ver" type="int" use="required"></attribute>
		<attribute name="title" type="string" use="required"></attribute>
		<attribute name="type" type="int" use="required"></attribute>
		<attribute name="eeprom-size" type="int" use="required"></attribute>
		<attribute name="last-change" type="int" use="optional"></attribute>
	</complexType>

	<complexType name="inputType"></complexType>

	<complexType name="outputType"></complexType>

	<complexType name="variableType">
		<sequence>
			<element name="description" type="string" maxOccurs="1"
				minOccurs="0">
			</element>
			<choice>
				<element name="number" type="tns:numberType"></element>
				<element name="choice" type="tns:choiceType"></element>
				<element name="array" type="tns:arrayType"></element>

			</choice>
		</sequence>
		<attribute name="offset" type="string" use="required"></attribute>
		<attribute name="reload" type="boolean" use="optional"></attribute>
		<attribute name="name" type="string" use="required"></attribute>
	</complexType>

	<complexType name="choiceType">
		<sequence>
			<element name="choice-entry" type="tns:choiceEntryType" maxOccurs="unbounded" minOccurs="1"></element>
			<element name="description" type="string" maxOccurs="1" minOccurs="0"></element>
		</sequence>
		<attribute name="length" type="int" use="required"></attribute>
		<attribute name="default" type="string" use="optional"></attribute>
	</complexType>

	<complexType name="numberType">
		<attribute name="length" type="int" use="required"></attribute>
		<attribute name="min-value" type="int" use="optional"></attribute>
		<attribute name="max-value" type="int" use="optional"></attribute>
		<attribute name="default" type="int" use="optional"></attribute>
		<attribute name="pattern" type="string" use="optional"></attribute>
	</complexType>

	<complexType name="arrayType">
		<sequence>
			<element name="entry" type="tns:variableType"></element>
		</sequence>
		<attribute name="count" type="string" use="required"></attribute>
		<attribute name="element-size" type="string" use="required"></attribute>
	</complexType>

	<complexType name="choiceEntryType">
		<sequence>
			<element name="description" type="string" maxOccurs="1" minOccurs="0"></element>
		</sequence>
		<attribute name="value" type="int" use="required"></attribute>
		<attribute name="name" type="string" use="required"></attribute>
	</complexType>
</schema>

=== koa/hs485-comm/src/main/resources/ch/eleveneye/hs485/config/hs485-types.xml
<?xml version="1.0" encoding="UTF-8"?>
<hs485 xmlns="http://www.eleveneye.ch/HS485-Schema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/HS485-Schema HS485-Schema.xsd ">
	<module sw-ver="200" hw-ver="1" type="0" title="HS485D"
		eeprom-size="512" class="ch.eleveneye.hs485.device.HS485D">
		<variable name="keymode" offset="0" reload="true">
			<choice length="1" default="split-keys">
				<choice-entry value="0" name="split-keys">
					<description>Zwei einfache Taster</description>
				</choice-entry>
				<choice-entry value="1" name="join-keys">
					<description>Ein Taster Hoch/Runter</description>
				</choice-entry>
				<description>
					Das Modul HS485D besitzt zwei Eingänge. Wird die
					Option "Zwei einfache Taster" gewählt, könnnen diese
					als zwei getrennt geschaltete Eingänge genutzt
					werden. Diese Eingänge können mit den Ausgängen
					anderer Module verknüpft werden.

					Wird die Option "Ein Taster Hoch/Runter" ausgewählt,
					so kann mit Eingang T2 ein Ausgang ausgeschaltet,
					bzw. runtergefahren und mit Eingang T1 ein Ausgang
					eingeschaltet, bzw. hochgefahren werden. Die beiden
					Tastereingänge gehören also logisch zusammen.
				</description>
			</choice>
		</variable>
		<variable name="input-type" offset="0x12" reload="true">
			<array element-size="1" count="2">
				<entry name="type" offset="0x00">
					<choice length="1">
						<choice-entry name="key-with-led" value="255">
							<description>
								Taster-Eingang mit LED
							</description>
						</choice-entry>
						<choice-entry name="key-without-led"
							value="1">
							<description>
								Taster-Eingang ohne LED
							</description>
						</choice-entry>
						<choice-entry name="switch-with-led"
							value="2">
							<description>
								Schalter-Eingang mit LED
							</description>
						</choice-entry>
						<choice-entry name="switch-without-led"
							value="3">
							<description>
								Schalter-Eingang ohne LED
							</description>
						</choice-entry>
					</choice>
				</entry>
			</array>
		</variable>
	</module>
</hs485>
